server.port: ${cute-name-service.port}

opentracing:
  jaeger:
    http-sender:
      url: ${jaeger.endpoint}
    enable-b3-propagation: true
    log-spans: true
spring:
  application:
    name: ${project.artifactId}
