apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: greeting-redir
spec:
  destination:
    name: spring-boot-istio-distributed-tracing-greeting-service
  match:
    request:
      headers:
        uri:
          prefix: /greeting # prefix
  rewrite:
    uri: /  # drop the /suggest prefix when talking to suggestion-service service such as /greeting/api/whatever -> /api/whatever